### ISSUE TITLE
question about configs/recognition/SSTFormer/SSTFormer.py

### ISSUE THREAD

**Issue by Bin1119** [Event-AHU/SSTFormer#1]
Hello, I have downloaded your PokerEvent dataset, and try to run your code. But I found that configs/recognition/SSTFormer/SSTFormer py did not specify how the dataset parameters should be set. 
```
# ##rgb_Puke100
dataset_type = 'RawframeDataset'
data_root = 
data_root_val = 
ann_file_train =
ann_file_val = 
ann_file_test =
```
Can you explain how the above parameters should be set?

**Comment by WuZongzhen** [comment]
This section is the dataset path, you can check the updated code.

**Comment by Bin1119** [comment]
```
dataset_type = 'RawframeDataset'
data_root = '.../Poker_rgbframes/'
data_root_val = '.../Poker_rgbframes/'
ann_file_train ='.../train_label.txt'
ann_file_val = '.../val_label.txt'
ann_file_test ='.../test_label.txt'
```
![1](https://github.com/Event-AHU/SSTFormer/assets/28151003/a7351945-97f6-44c2-aaa9-35a9ccdcda4e)
I see that train_label.txt, val_label.txt and test_label.txt are in the Poker_list folder of the dataset you provided, but I did not find 'Poker_rgbframes' folder. PokerEvent.zip is unzipped to multiple folders containing .aedat4 files.

**Comment by Bin1119** [comment]
> This section is the dataset path, you can check the updated code.
Seems to require a dataset preprocessing code to get the data_root and data_root_val in the configuration file, can you help?

**Comment by Bin1119** [comment]
According to my understanding, I modified the dataset path you gave into the dataset path I downloaded.
```
dataset_type = 'RawframeDataset'
data_root = '/workspace/shared/event_dataset/PokerEvent/'
data_root_val = '/workspace/shared/event_dataset/PokerEvent/'
ann_file_train ='/workspace/shared/event_dataset/PokerEvent/Poker_list/train_label.txt'
ann_file_val = '/workspace/shared/event_dataset/PokerEvent/Poker_list/val_label.txt'
ann_file_test ='/workspace/shared/event_dataset/PokerEvent/Poker_list/test_label.txt'
```
I then ran the training code provided in README.md.
```
python tools/train.py configs/recognition/SSTFormer/SSTFormer.py --work-dir work_dirs/SSTFormer  --seed 0 --deterministic
```
But an error occurs when running the code:
```
KeyError: 'SSTFormer is not in the mmaction::model registry. Please check whether the value of `SSTFormer` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'
```
The code version is your latest update, and I don't know what's wrong.

**Comment by wangxiao5791509** [comment]
@WuZongzhen

**Comment by WuZongzhen** [comment]
> > This section is the dataset path, you can check the updated code.
> > Seems to require a dataset preprocessing code to get the data_root and data_root_val in the configuration file, can you help?

You can refer to the code in the folder "data processing" to process the dataset
