### ISSUE TITLE
SSTFormer

### ISSUE THREAD

**Issue by a1wj1** [Event-AHU/SSTFormer#3]
May I ask if SSTFormer refers to the SCNN-MST method mentioned in the paper? Does SpikingF-MST refer to the Spikingformer-MST method？

**Comment by wangxiao5791509** [comment]
@a1wj1  yes.

**Comment by a1wj1** [comment]
May I ask if you only disclose the code for SpikingF-MST? I did not see any related scripts for the SCNN-MST model in the project?

**Comment by wangxiao5791509** [comment]
![image](https://github.com/Event-AHU/SSTFormer/assets/12805786/79cec77c-5508-4b1f-a298-8959239449e7)


@a1wj1
