### ISSUE TITLE
config

### ISSUE THREAD

**Issue by a1wj1** [Event-AHU/SSTFormer#5]
I have another idea that in the config file, .../Poker_rgbframes/ refer to the folder that contains the aedat4 format files after decompression? Also, when training the PokerEvent dataset, is it only using one GPU? Thank you for your reply!

**Comment by a1wj1** [comment]
![1705287251942](https://github.com/Event-AHU/SSTFormer/assets/38905689/37da3ddf-b4eb-407f-8a12-40549ea8e8ae)

I found this error, does this mean that this folder is storing the png file exported by read_aedat4.py?

**Comment by WuZongzhen** [comment]
You can refer to the code in the folder "data processing" to process the dataset

**Comment by a1wj1** [comment]
![1705287359589](https://github.com/Event-AHU/SSTFormer/assets/38905689/3bb2c270-4c94-490c-8449-0ea7857866e7)

Thank you! I have seen it in mmaction/datasets/rawframe_ Dataset.py, but when I run it, I will report an error. The error is in SSTFormer main/maction2/mmaction/datasets/transformers/loading. py. Do you know why this is happening?
