### ISSUE TITLE
代码报错

### ISSUE THREAD

**Issue by a1wj1** [Event-AHU/SSTFormer#7]
你好，使用了data_processing之后，目前还有这个问题，请问这个路径的代码是不是写错了？

![1705314378185](https://github.com/Event-AHU/SSTFormer/assets/38905689/fc1923a3-9e4c-4c17-bca1-bd2e11ec4cec)

这部分代码是为了读取event事件的信息吗，是不是需要自行修改路径？
![1705313137068](https://github.com/Event-AHU/SSTFormer/assets/38905689/95e1177a-5131-4e2f-ac16-a2fac59d54d0)

**Comment by WuZongzhen** [comment]
这部分要自行修改成Event部分的路径
